### ISSUE TITLE
Release training code

### ISSUE THREAD

**Issue by codingbaobao** [nkolkin13/STROTSS#11]
Is it possible to release your training code?

**Comment by nkolkin13** [comment]
Hi! This method (and many other style transfer methods) don't require any training. It uses VGG-16 pretrained on imagenet classification to extract features, but we don't train anything from scratch. We directly optimize the pixels of the output image based on these features, and this optimization is unique to each content/style input pair.

**Comment by codingbaobao** [comment]
Oh, okay. Looks like i misunderstand it...
