### ISSUE TITLE
What Python is this?

### ISSUE THREAD

**Issue by nerdogram** [nkolkin13/STROTSS#13]
Thanks for the code but I think its broken now.

from .st_helper import *
gives error
ModuleNotFoundError: No module named '__main__.st_helper'; '__main__' is not a package

Never seen imports like this. Is this some new Python feature?

Once I fixed all the periods I still ended up with an error on max scale of List Index out of range on the inference script.

**Comment by nkolkin13** [comment]
Hi, it's python 3. (It was written/debugged with python 3.5 I think, and I can run it on python 3.6 currently)

That's a relative import, 'from .st_helper' just means that 'st_helper.py' is in the same directory as the file that's importing functions from it.

Could you post what you ran in the command line, and the error trace? I will try to take a look

**Comment by nerdogram** [comment]
I'm trying to run this on a Colab which uses Python 3.6+ and it errors out.

!python styleTransfer.py '/content/input.jpg' '/content/style.jpg' 0.5

Error:

`Traceback (most recent call last):
  File "styleTransfer.py", line 12, in <module>
    from  .st_helper import *
ModuleNotFoundError: No module named '__main__.st_helper'; '__main__' is not a package`

It doesn't like the period. But the bigger issue is when I do fix all the periods it still fails with a List Index out of range error on this line:

 max_scl = int(sys.argv[4])

**Comment by nkolkin13** [comment]
So I don't know how my code will interact with colab, it's intended to be run from the command line. If that line is failing it's because you aren't passing in all the required arguments, passing in 4 or 5 will work, or you can just hardcode it.

**Comment by nkolkin13** [comment]
I updated the readme to reflect that you need the extra argument, sorry about that, I must have switched it from being hardcoded to a command line argument when I updated the feature extraction.
