### ISSUE TITLE
question about processing time at each scale

### ISSUE THREAD

**Issue by lulu1315** [nkolkin13/STROTSS#2]
hello nick
while testing your code I noticed the processing time at each scale.
on the example I'm working on :
scl1 (long side 64): 250 iters takes 87s
scl2 (long side 128): 250 iters takes 63s
scl3 (long side 256): 250 iters takes 54s
scl4 (long side 512): 250 iters takes 60s
scl5 (long side 1024): 250 iters takes 98s

intuitively I would have thought the lower scales should be much faster that the upper scales.
because of the size of the tensors.
would it make sense to use less iterations at lower scale for example (CNNMRF gives you the ability to choose the number of iterations at each scale)
just wondering ?
luc

**Comment by nkolkin13** [comment]
Hi Luc,

In my experiments the first 3 scales take an equal amount of time, and then it increases for scales 4 and 5. I'm sorry, but I'm not sure why your first scale is taking longer than scales 2 or 3 (or why scale 4 is has equal speed to 3).

I assume that for lower scales the overhead of computing the REMD is dominating the cost of updating the image pixels with RMSprop, but I haven't tried profiling it. 

For simplicity I kept the number of iterations the same at each scale, but it would certainly make sense to play with that to try and get a speedup.

I probably won't update the code before the NeurIPS deadline, but I'll revisit the code in late May. Thank you for your suggestions!

Best,
Nick

**Comment by lulu1315** [comment]
thanks for the reply nick.I'm having a lot of fun playing with the code right now.
I tried to fix an output resolution and a number of scales and derive the smll_sz value from it.
it works but I don't know if it makes sense in your logic.let me know if it's absurd :)

the beautiful thing would be to do something with optical flow for temporal coherence ...
cheers
luc

**Comment by nkolkin13** [comment]
Glad you're having fun with it!

That makes total sense, and it's a good idea.

Yes that would be very cool, this paper might interest you if you haven't seen it https://arxiv.org/pdf/1604.08610.pdf (sorry if you have). I'm sure there is more recent work on the area, but it's not something I follow closely, I'd bet they everything more recent cites that paper though.

**Comment by lulu1315** [comment]
hello Nick.well I used Ruder's code a lot.also CNNMRF and of course jcjohnson's.
I'm currently trying your code on animated sequences.
I'm naively blending optical flow warped previously processed frame with current frame and the results are pretty interesting.
the global shapes stays pretty consistent but there's a low frequency flickering.
blind consistency helps but makes it a little blurry to my taste.
I'm generating 1920x1080 frames on a TitanX with 12M memory which is very cool!

**Comment by nkolkin13** [comment]
Hi Luc,
I saw the video (which I assume you made) on youtube, whatever you added to make it work for video is working really nicely! You mention some low frequency flickering, I'm not sure how your optical flow stabilization is applied, but if it's as a regularization term that directly affects the optimization then one option would be to apply the loss in the fourier domain, then you can control it's strength directly at different frequencies. Thank you for using the code, I was super excited to see the video!
Best,
Nick

**Comment by lulu1315** [comment]
hello Nick.In fact I didn't touch your code for the opticalflow.I'm just blending the warped previous result with the current content , then go through your code.the flickering , I think , may come from the pyramidal nature or maybe due to the random parts of your code.
it would be a blast if you have time to work on a temporal stability of your solution.
thanks for the good words.Luc

**Comment by lulu1315** [comment]
hello Nick.I uploaded my latest tests with strotss.
https://www.youtube.com/watch?v=CM6Sufx6qT0&feature=youtu.be
i hope you'll enjoy it and thanks again for your work.
luc
