### ISSUE TITLE
Hi Nick! Great Paper, I had a small doubt!

### ISSUE THREAD

**Issue by AdarshMJ** [nkolkin13/STROTSS#4]
In section 2 of the paper, where you preface about the objective function you say,

> We describe the content term of our loss αlC in Section 2.2, and the style term lm + lr + 1/a lp in Section 2.3. 

But section 2.2 talks about the style loss and section 2.3 talks about the content loss, is this right? If I have understood it right, αlC is the content loss and lm + lr + 1/a lp is the style loss, is this right? Pardon me if I have misunderstood it. Thanks in advance.

**Comment by nkolkin13** [comment]
Hi Adarsh,
Thank you for pointing out the typo. It should read:

> We describe the content term of our loss αlC in Section 2.3, and the style term lm + lr + 1/a lp in Section 2.2.

Best,
Nick
