### ISSUE TITLE
[Q] Speed up the code

### ISSUE THREAD

**Issue by GlebSBrykin** [nkolkin13/STROTSS#5]
Great project! I am interested in Your work and would like to implement it in C#. I would like to know how to speed up the code as much as possible? What parameters could I change?

**Comment by nkolkin13** [comment]
Hi Gleb,
Thank you for your interest! The best bet for speeding things up is probably playing with the number of iterations per resolution, you can probably reduce the number of iterations at higher resolutions without too much impact on the output's visual quality.
Best,
Nick
